/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.iia.MegaCasting;

import fr.iia.Class.Adresse;
import fr.iia.Class.Annonceur;
import fr.iia.Class.Article;
import fr.iia.Class.Diffuseur;
import fr.iia.Class.Evenement;
import fr.iia.Class.Musique;
import fr.iia.Class.Offre;
import fr.iia.Connection.JavaConnect;
import static fr.iia.Connection.JavaConnect.ConnectDB;
import static fr.iia.Connection.JavaConnect.ImportDriver;
import fr.iia.DAO.AnnonceursDAO;
import fr.iia.DAO.ArticleDAO;
import fr.iia.DAO.DiffuseursDAO;
import fr.iia.DAO.EvenementDAO;
import fr.iia.DAO.MusiqueDAO;
import fr.iia.DAO.OffreDAO;
import java.awt.Dialog;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Collection;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Enzo
 */
public class MegaCastingMain extends javax.swing.JFrame {

    Connection cnx = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form MegaCastingMain Sylvain Davenel Florian Samson
     */
    public MegaCastingMain() {
        initComponents();
        ImportDriver();
        cnx = JavaConnect.ConnectDB();
        refreshAllList();
    }

    private void offreListe() {
        DefaultTableModel model = (DefaultTableModel) offreTab.getModel();
        model.setNumRows(0);
        OffreDAO offreDAO = new OffreDAO();
        Collection<Offre> offre = offreDAO.lister(cnx);

        for (Offre o : offre) {
            model.addRow(new Object[]{
                o.getTitre(),
                o.getReference(),
                o.getDate_debut_publi(),
                o.getFin_publi(),
                o.getNbr_poste(),
                o.getDescription_poste(),
                o.getDescription_profil(),
                o.getDuree(),
                o.getContrat(),
                o.getAnnonceur(),
                o.getDiffuseur(),
                o.getMetier()
            });
        }
    }

    public void paintComponent(Graphics g) {
        try {
            Image img = ImageIO.read(new File("Fond.jpg"));
            //g.drawImage(img, 50, 50, this);
            //Pour une image de fond
            g.drawImage(img, 50, 50, this.getWidth(), this.getHeight(), this);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        page = new javax.swing.JTabbedPane();
        AccueilPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        offrePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        offreTab = new javax.swing.JTable();
        supprimerOffreBouton = new javax.swing.JButton();
        annonceurPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        annonceurTab = new javax.swing.JTable();
        supprimerAnnonceurBouton = new javax.swing.JButton();
        diffuseurPanel = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        diffuseurTab = new javax.swing.JTable();
        supprimerDiffuseurBouton = new javax.swing.JButton();
        evenementPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        evenementTab = new javax.swing.JTable();
        supprimerEvenementBouton = new javax.swing.JButton();
        musiquePanel = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        musiqueTab = new javax.swing.JTable();
        supprimerMusiqueBouton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        articleTab = new javax.swing.JTable();
        Supprimer_article = new javax.swing.JButton();
        barreMenu = new javax.swing.JMenuBar();
        fichierMenu = new javax.swing.JMenu();
        ajouterMenuFichier = new javax.swing.JMenu();
        offreMenuAjouter = new javax.swing.JMenuItem();
        annonceurMenuAjouter = new javax.swing.JMenuItem();
        diffuseurMenuAjouter = new javax.swing.JMenuItem();
        evenementMenuAjouter = new javax.swing.JMenuItem();
        musiqueMenuAjouter = new javax.swing.JMenuItem();
        articleMenuAjouter1 = new javax.swing.JMenuItem();
        ModifierMenuFichier = new javax.swing.JMenu();
        offreMenuModifier = new javax.swing.JMenuItem();
        annonceurMenuModifier = new javax.swing.JMenuItem();
        diffuseurMenuModifier = new javax.swing.JMenuItem();
        evenementMenuModifier = new javax.swing.JMenuItem();
        musiqueMenuModifier = new javax.swing.JMenuItem();
        articleMenuModifier1 = new javax.swing.JMenuItem();
        quitterMenuFichier = new javax.swing.JMenuItem();
        editionMenu = new javax.swing.JMenu();
        aideMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Méga Casting");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/petitLogo.png"))); // NOI18N

        jButton1.setText("RefreshList");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AccueilPanelLayout = new javax.swing.GroupLayout(AccueilPanel);
        AccueilPanel.setLayout(AccueilPanelLayout);
        AccueilPanelLayout.setHorizontalGroup(
            AccueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilPanelLayout.createSequentialGroup()
                .addGroup(AccueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AccueilPanelLayout.createSequentialGroup()
                        .addGap(428, 428, 428)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(AccueilPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)))
                .addContainerGap(360, Short.MAX_VALUE))
        );
        AccueilPanelLayout.setVerticalGroup(
            AccueilPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AccueilPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jButton1)
                .addGap(86, 86, 86)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        page.addTab("Accueil", AccueilPanel);

        offreTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre", "Référence", "Début publication", "Fin publication", "Nombre de poste", "Description du poste", "Description du profil", "Durée du contrat(mois)", "Contrat", "Annonceur", "Diffuseur", "Metier"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        offreTab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                offreTabMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(offreTab);

        supprimerOffreBouton.setText("Supprimer");
        supprimerOffreBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerOffreBoutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout offrePanelLayout = new javax.swing.GroupLayout(offrePanel);
        offrePanel.setLayout(offrePanelLayout);
        offrePanelLayout.setHorizontalGroup(
            offrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(offrePanelLayout.createSequentialGroup()
                .addGroup(offrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(offrePanelLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(supprimerOffreBouton))
                    .addGroup(offrePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        offrePanelLayout.setVerticalGroup(
            offrePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, offrePanelLayout.createSequentialGroup()
                .addComponent(supprimerOffreBouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        page.addTab("Offres", offrePanel);

        annonceurTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Email", "Telephone", "N° rue", "Nom rue", "Code Postal", "Ville"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(annonceurTab);

        supprimerAnnonceurBouton.setText("Supprimer");
        supprimerAnnonceurBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerAnnonceurBoutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout annonceurPanelLayout = new javax.swing.GroupLayout(annonceurPanel);
        annonceurPanel.setLayout(annonceurPanelLayout);
        annonceurPanelLayout.setHorizontalGroup(
            annonceurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(annonceurPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(annonceurPanelLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(supprimerAnnonceurBouton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        annonceurPanelLayout.setVerticalGroup(
            annonceurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, annonceurPanelLayout.createSequentialGroup()
                .addComponent(supprimerAnnonceurBouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        page.addTab("Annonceurs", annonceurPanel);

        diffuseurTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Email", "Telephone", "N° rue", "Nom rue", "Code Postal", "Ville"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        diffuseurTab.setColumnSelectionAllowed(true);
        jScrollPane6.setViewportView(diffuseurTab);
        diffuseurTab.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        supprimerDiffuseurBouton.setText("Supprimer");
        supprimerDiffuseurBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerDiffuseurBoutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diffuseurPanelLayout = new javax.swing.GroupLayout(diffuseurPanel);
        diffuseurPanel.setLayout(diffuseurPanelLayout);
        diffuseurPanelLayout.setHorizontalGroup(
            diffuseurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diffuseurPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(diffuseurPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(supprimerDiffuseurBouton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        diffuseurPanelLayout.setVerticalGroup(
            diffuseurPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diffuseurPanelLayout.createSequentialGroup()
                .addComponent(supprimerDiffuseurBouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        page.addTab("Diffuseurs", diffuseurPanel);

        evenementTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nom", "Description", "Date", "N° Rue", "Nom Rue", "Code Postal", "Ville", "Annonceur"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(evenementTab);

        supprimerEvenementBouton.setText("Supprimer");
        supprimerEvenementBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerEvenementBoutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout evenementPanelLayout = new javax.swing.GroupLayout(evenementPanel);
        evenementPanel.setLayout(evenementPanelLayout);
        evenementPanelLayout.setHorizontalGroup(
            evenementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(evenementPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(evenementPanelLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(supprimerEvenementBouton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        evenementPanelLayout.setVerticalGroup(
            evenementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, evenementPanelLayout.createSequentialGroup()
                .addComponent(supprimerEvenementBouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        page.addTab("Evenements", evenementPanel);

        musiqueTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Titre", "Description", "Genre", "Artiste"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(musiqueTab);

        supprimerMusiqueBouton.setText("Supprimer");
        supprimerMusiqueBouton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerMusiqueBoutonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout musiquePanelLayout = new javax.swing.GroupLayout(musiquePanel);
        musiquePanel.setLayout(musiquePanelLayout);
        musiquePanelLayout.setHorizontalGroup(
            musiquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musiquePanelLayout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(musiquePanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(supprimerMusiqueBouton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        musiquePanelLayout.setVerticalGroup(
            musiquePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(musiquePanelLayout.createSequentialGroup()
                .addComponent(supprimerMusiqueBouton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        page.addTab("Musiques", musiquePanel);

        articleTab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nom", "Prix", "Description"
            }
        ));
        jScrollPane7.setViewportView(articleTab);

        Supprimer_article.setText("Supprimer");
        Supprimer_article.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Supprimer_articleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(Supprimer_article)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(Supprimer_article)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        page.addTab("Articles", jPanel1);

        barreMenu.setFocusable(false);

        fichierMenu.setText("Fichier");

        ajouterMenuFichier.setText("Ajouter");

        offreMenuAjouter.setText("Offres");
        offreMenuAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offreMenuAjouterActionPerformed(evt);
            }
        });
        ajouterMenuFichier.add(offreMenuAjouter);

        annonceurMenuAjouter.setText("Annonceurs");
        annonceurMenuAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annonceurMenuAjouterActionPerformed(evt);
            }
        });
        ajouterMenuFichier.add(annonceurMenuAjouter);

        diffuseurMenuAjouter.setText("Diffuseurs");
        diffuseurMenuAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffuseurMenuAjouterActionPerformed(evt);
            }
        });
        ajouterMenuFichier.add(diffuseurMenuAjouter);

        evenementMenuAjouter.setText("Evènements");
        evenementMenuAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evenementMenuAjouterActionPerformed(evt);
            }
        });
        ajouterMenuFichier.add(evenementMenuAjouter);

        musiqueMenuAjouter.setText("Musiques");
        musiqueMenuAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musiqueMenuAjouterActionPerformed(evt);
            }
        });
        ajouterMenuFichier.add(musiqueMenuAjouter);

        articleMenuAjouter1.setText("Articles");
        articleMenuAjouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleMenuAjouter1ActionPerformed(evt);
            }
        });
        ajouterMenuFichier.add(articleMenuAjouter1);

        fichierMenu.add(ajouterMenuFichier);

        ModifierMenuFichier.setText("Modifier");

        offreMenuModifier.setText("Offres");
        offreMenuModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offreMenuModifierActionPerformed(evt);
            }
        });
        ModifierMenuFichier.add(offreMenuModifier);

        annonceurMenuModifier.setText("Annonceurs");
        annonceurMenuModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annonceurMenuModifierActionPerformed(evt);
            }
        });
        ModifierMenuFichier.add(annonceurMenuModifier);

        diffuseurMenuModifier.setText("Diffuseurs");
        diffuseurMenuModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffuseurMenuModifierActionPerformed(evt);
            }
        });
        ModifierMenuFichier.add(diffuseurMenuModifier);

        evenementMenuModifier.setText("Evènements");
        evenementMenuModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evenementMenuModifierActionPerformed(evt);
            }
        });
        ModifierMenuFichier.add(evenementMenuModifier);

        musiqueMenuModifier.setText("Musiques");
        musiqueMenuModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                musiqueMenuModifierActionPerformed(evt);
            }
        });
        ModifierMenuFichier.add(musiqueMenuModifier);

        articleMenuModifier1.setText("Articles");
        articleMenuModifier1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                articleMenuModifier1ActionPerformed(evt);
            }
        });
        ModifierMenuFichier.add(articleMenuModifier1);

        fichierMenu.add(ModifierMenuFichier);

        quitterMenuFichier.setText("Quitter");
        quitterMenuFichier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitterMenuFichierActionPerformed(evt);
            }
        });
        fichierMenu.add(quitterMenuFichier);

        barreMenu.add(fichierMenu);

        editionMenu.setText("Edition");
        barreMenu.add(editionMenu);

        aideMenu.setText("Aide");
        aideMenu.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        aideMenu.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        jMenuItem1.setText("Docs  en ligne et support");
        aideMenu.add(jMenuItem1);

        jMenuItem2.setText("A propos");
        aideMenu.add(jMenuItem2);

        barreMenu.add(aideMenu);

        setJMenuBar(barreMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(page, javax.swing.GroupLayout.PREFERRED_SIZE, 1007, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(page, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshAllList() {
        refreshListEvenement();
        refreshListAnnonceur();
        refreshListDiffuseur();
        refreshListMusique();
        refreshListOffre();
        refreshListArticle();
    }

    private void refreshListAnnonceur() {
        DefaultTableModel model = (DefaultTableModel) annonceurTab.getModel();
        model.setNumRows(0);

        AnnonceursDAO annonceurDao = new AnnonceursDAO();
        Collection<Annonceur> annonceurs = AnnonceursDAO.lister(cnx);

        for (Annonceur a : annonceurs) {
            model.addRow(new Object[]{
                a.getNom(),
                a.getMail(),
                a.getNumeroTel(),
                a.getAdresse().getNumero(),
                a.getAdresse().getRue(),
                a.getAdresse().getCodePostal(),
                a.getAdresse().getVille(),});
        }
    }

    private void refreshListDiffuseur() {
        DefaultTableModel model = (DefaultTableModel) diffuseurTab.getModel();
        model.setNumRows(0);

        DiffuseursDAO diffuseurDAO = new DiffuseursDAO();
        Collection<Diffuseur> diffuseurs = DiffuseursDAO.lister(cnx);

        for (Diffuseur d : diffuseurs) {
            model.addRow(new Object[]{
                d.getNom(),
                d.getMail(),
                d.getNumeroTel(),
                d.getAdresse().getNumero(),
                d.getAdresse().getRue(),
                d.getAdresse().getCodePostal(),
                d.getAdresse().getVille(),});
        }
    }

    private void refreshListOffre() {
        DefaultTableModel model = (DefaultTableModel) offreTab.getModel();
        model.setNumRows(0);

        OffreDAO offreDAO = new OffreDAO();
        Collection<Offre> offres = OffreDAO.lister(cnx);

        for (Offre o : offres) {
            model.addRow(new Object[]{
                o.getTitre(),
                o.getReference(),
                o.getDate_debut_publi(),
                o.getFin_publi(),
                o.getNbr_poste(),
                o.getDescription_poste(),
                o.getDescription_profil(),
                o.getDuree(),
                o.getContrat().getLibelle(),
                o.getAnnonceur().getNom(),
                o.getDiffuseur().getNom(),
                o.getMetier().getLibelle()
            });
        }
    }

    private void refreshListEvenement() {
        DefaultTableModel model = (DefaultTableModel) evenementTab.getModel();
        model.setNumRows(0);

        EvenementDAO evenementDAO = new EvenementDAO();
        Collection<Evenement> evenements = EvenementDAO.lister(cnx);

        for (Evenement event : evenements) {
            model.addRow(new Object[]{
                event.getNom(),
                event.getDescription(),
                event.getDateEvenement(),
                event.getAdresse().getNumero(),
                event.getAdresse().getRue(),
                event.getAdresse().getCodePostal(),
                event.getAdresse().getVille(),
                event.getAnnonceur().getNom()
            });
        }
    }

    private void refreshListMusique() {
        DefaultTableModel model = (DefaultTableModel) musiqueTab.getModel();
        model.setNumRows(0);

        MusiqueDAO musiqueDAO = new MusiqueDAO();
        Collection<Musique> musiques = MusiqueDAO.lister(cnx);

        for (Musique m : musiques) {
            model.addRow(new Object[]{
                m.getTitre(),
                m.getDescription(),
                m.getGenre(),
                m.getUtilisateur().getNom_artiste()
            });
        }
    }

    private void refreshListArticle() {
        DefaultTableModel model = (DefaultTableModel) articleTab.getModel();
        model.setNumRows(0);

        ArticleDAO articleDAO = new ArticleDAO();
        Collection<Article> articles = ArticleDAO.lister(cnx);

        for (Article a : articles) {
            model.addRow(new Object[]{
                a.getNom(),
                a.getPrix(),
                a.getDescription()
            });
        }

    }

    private void evenementMenuAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evenementMenuAjouterActionPerformed
        // TODO add your handling code here
        ajouterEvenement ajouterEvenementFrame = new ajouterEvenement();
        ajouterEvenementFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // ajouterEvenementFrame.setSize(600, 600);
        ajouterEvenementFrame.setVisible(true);
    }//GEN-LAST:event_evenementMenuAjouterActionPerformed

    private void offreMenuAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offreMenuAjouterActionPerformed
        // TODO add your handling code here:
        ajouterOffre ajouterOffreFrame = new ajouterOffre();
        ajouterOffreFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // ajouterOffreFrame.setSize(1000, 600);
        ajouterOffreFrame.setVisible(true);
    }//GEN-LAST:event_offreMenuAjouterActionPerformed

    private void annonceurMenuAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annonceurMenuAjouterActionPerformed
        // TODO add your handling code here:
        ajouterAnnonceur ajouterAnnonceurFrame = new ajouterAnnonceur();
        ajouterAnnonceurFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // ajouterAnnonceurFrame.setSize(600, 600);
        ajouterAnnonceurFrame.setVisible(true);
    }//GEN-LAST:event_annonceurMenuAjouterActionPerformed

    private void diffuseurMenuAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffuseurMenuAjouterActionPerformed
        // TODO add your handling code here:
        ajouterDiffuseur ajouterDiffuseurFrame = new ajouterDiffuseur();
        ajouterDiffuseurFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        ajouterDiffuseurFrame.setResizable(false);
        ajouterDiffuseurFrame.setLocationRelativeTo(null);
        ajouterDiffuseurFrame.setVisible(true);
    }//GEN-LAST:event_diffuseurMenuAjouterActionPerformed

    private void musiqueMenuAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musiqueMenuAjouterActionPerformed
        // TODO add your handling code here:
        ajouterMusique ajouterMusiqueFrame = new ajouterMusique();
        ajouterMusiqueFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // ajouterMusiqueFrame.setSize(600, 600);
        ajouterMusiqueFrame.setVisible(true);
    }//GEN-LAST:event_musiqueMenuAjouterActionPerformed

    private void quitterMenuFichierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitterMenuFichierActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitterMenuFichierActionPerformed

    private void offreMenuModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offreMenuModifierActionPerformed
        // TODO add your handling code here:
        modifierOffre modifierOffreFrame = new modifierOffre();
        modifierOffreFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // ajouterOffreFrame.setSize(1000, 600);
        modifierOffreFrame.setVisible(true);


    }//GEN-LAST:event_offreMenuModifierActionPerformed

    private void annonceurMenuModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annonceurMenuModifierActionPerformed
        modifierAnnonceur modifierAnnonceurFrame = new modifierAnnonceur();
        modifierAnnonceurFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        modifierAnnonceurFrame.setVisible(true);
    }//GEN-LAST:event_annonceurMenuModifierActionPerformed

    private void diffuseurMenuModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffuseurMenuModifierActionPerformed

        modifierDiffuseur modifierDiffuseurFrame = new modifierDiffuseur();
        modifierDiffuseurFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        modifierDiffuseurFrame.setVisible(true);

    }//GEN-LAST:event_diffuseurMenuModifierActionPerformed

    private void evenementMenuModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evenementMenuModifierActionPerformed
        // TODO add your handling code here:
        modifierEvenement modifierEvenementFrame = new modifierEvenement();
        modifierEvenementFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        modifierEvenementFrame.setVisible(true);


    }//GEN-LAST:event_evenementMenuModifierActionPerformed

    private void musiqueMenuModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_musiqueMenuModifierActionPerformed
        modifierMusique modifiermusiqueFrame = new modifierMusique();
        modifiermusiqueFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        modifiermusiqueFrame.setVisible(true);
    }//GEN-LAST:event_musiqueMenuModifierActionPerformed

    private void articleMenuAjouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleMenuAjouter1ActionPerformed
        // TODO add your handling code here:
        ajouterArticle ajouterArticleFrame = new ajouterArticle();
        ajouterArticleFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // ajouterOffreFrame.setSize(1000, 600);
        ajouterArticleFrame.setVisible(true);
    }//GEN-LAST:event_articleMenuAjouter1ActionPerformed

    private void articleMenuModifier1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_articleMenuModifier1ActionPerformed
        // TODO add your handling code here:
        modifierArticle modifierArticleFrame = new modifierArticle();
        modifierArticleFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        // ajouterOffreFrame.setSize(1000, 600);
        modifierArticleFrame.setVisible(true);
    }//GEN-LAST:event_articleMenuModifier1ActionPerformed

    private void supprimerMusiqueBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerMusiqueBoutonActionPerformed
        // TODO add your handling code here:
        Musique musiqueSelected = MusiqueDAO.lister(cnx).get(musiqueTab.getSelectedRow());

        if (musiqueSelected != null) {
            new MusiqueDAO().supprimer(cnx, musiqueSelected);
        }
        refreshListMusique();
    }//GEN-LAST:event_supprimerMusiqueBoutonActionPerformed

    private void supprimerEvenementBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerEvenementBoutonActionPerformed
        // TODO add your handling code here:
        Evenement evenementSelected = EvenementDAO.lister(cnx).get(evenementTab.getSelectedRow());

        if (evenementSelected != null) {
            new EvenementDAO().supprimer(cnx, evenementSelected);
        }
        refreshListEvenement();
    }//GEN-LAST:event_supprimerEvenementBoutonActionPerformed

    private void supprimerDiffuseurBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerDiffuseurBoutonActionPerformed
        // TODO add your handling code here:
        Diffuseur diffuseurSelected = DiffuseursDAO.lister(cnx).get(diffuseurTab.getSelectedRow());

        System.out.println("test");
        System.err.println("test2");
        if (diffuseurSelected != null) {
            new DiffuseursDAO().supprimer(cnx, diffuseurSelected);
        }
        refreshListDiffuseur();
    }//GEN-LAST:event_supprimerDiffuseurBoutonActionPerformed

    private void supprimerAnnonceurBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerAnnonceurBoutonActionPerformed
        // TODO add your handling code here:
        Annonceur annonceurSelected = AnnonceursDAO.lister(cnx).get(annonceurTab.getSelectedRow());

        if (annonceurSelected != null) {
            new AnnonceursDAO().supprimer(cnx, annonceurSelected);
        }
        refreshListAnnonceur();
    }//GEN-LAST:event_supprimerAnnonceurBoutonActionPerformed

    private void supprimerOffreBoutonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerOffreBoutonActionPerformed
        // TODO add your handling code here:
        Offre offreSelected = OffreDAO.lister(cnx).get(offreTab.getSelectedRow());

        if (offreSelected != null) {
            new OffreDAO().supprimer(cnx, offreSelected);
        }
        refreshListOffre();
    }//GEN-LAST:event_supprimerOffreBoutonActionPerformed

    private void offreTabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offreTabMouseClicked
        // TODO add your handling code here:
        try {
            int row = offreTab.getSelectedRow();
            String Table_click = (offreTab.getModel().getValueAt(row, 0).toString());
            String sql = "SELECT * FROM Offre WHERE id_offre ='" + Table_click + "' ";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_offreTabMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        refreshAllList();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Supprimer_articleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Supprimer_articleActionPerformed
        // TODO add your handling code here:
        Article articleSelected = ArticleDAO.lister(cnx).get(articleTab.getSelectedRow());

        if (articleSelected != null) {
            new ArticleDAO().supprimer(cnx, articleSelected);
        }
        refreshListArticle();
    }//GEN-LAST:event_Supprimer_articleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MegaCastingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MegaCastingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MegaCastingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MegaCastingMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MegaCastingMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AccueilPanel;
    private javax.swing.JMenu ModifierMenuFichier;
    private javax.swing.JButton Supprimer_article;
    private javax.swing.JMenu aideMenu;
    private javax.swing.JMenu ajouterMenuFichier;
    private javax.swing.JMenuItem annonceurMenuAjouter;
    private javax.swing.JMenuItem annonceurMenuModifier;
    private javax.swing.JPanel annonceurPanel;
    private javax.swing.JTable annonceurTab;
    private javax.swing.JMenuItem articleMenuAjouter1;
    private javax.swing.JMenuItem articleMenuModifier1;
    private javax.swing.JTable articleTab;
    private javax.swing.JMenuBar barreMenu;
    private javax.swing.JMenuItem diffuseurMenuAjouter;
    private javax.swing.JMenuItem diffuseurMenuModifier;
    private javax.swing.JPanel diffuseurPanel;
    private javax.swing.JTable diffuseurTab;
    private javax.swing.JMenu editionMenu;
    private javax.swing.JMenuItem evenementMenuAjouter;
    private javax.swing.JMenuItem evenementMenuModifier;
    private javax.swing.JPanel evenementPanel;
    private javax.swing.JTable evenementTab;
    private javax.swing.JMenu fichierMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JMenuItem musiqueMenuAjouter;
    private javax.swing.JMenuItem musiqueMenuModifier;
    private javax.swing.JPanel musiquePanel;
    private javax.swing.JTable musiqueTab;
    private javax.swing.JMenuItem offreMenuAjouter;
    private javax.swing.JMenuItem offreMenuModifier;
    private javax.swing.JPanel offrePanel;
    private javax.swing.JTable offreTab;
    private javax.swing.JTabbedPane page;
    private javax.swing.JMenuItem quitterMenuFichier;
    private javax.swing.JButton supprimerAnnonceurBouton;
    private javax.swing.JButton supprimerDiffuseurBouton;
    private javax.swing.JButton supprimerEvenementBouton;
    private javax.swing.JButton supprimerMusiqueBouton;
    private javax.swing.JButton supprimerOffreBouton;
    // End of variables declaration//GEN-END:variables
}
