/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.iia.MegaCasting;

import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import fr.iia.Class.Adresse;
import fr.iia.Class.Annonceur;
import fr.iia.Class.Contrat;
import fr.iia.Class.Diffuseur;
import fr.iia.Class.Domaine;
import fr.iia.Class.Evenement;
import fr.iia.Class.Media;
import fr.iia.Class.Metier;
import fr.iia.Class.Offre;
import fr.iia.Connection.JavaConnect;
import fr.iia.DAO.AnnonceursDAO;
import fr.iia.DAO.ContratDAO;
import fr.iia.DAO.DiffuseursDAO;
import fr.iia.DAO.EvenementDAO;
import fr.iia.DAO.MetierDAO;
import fr.iia.DAO.OffreDAO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.ZonedDateTime;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Flo
 */
public class modifierOffre extends javax.swing.JFrame {

    Connection cnx = null;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * Creates new form ajouterOffre
     */
    public modifierOffre() {
        initComponents();
        JavaConnect.ImportDriver();
        cnx = JavaConnect.ConnectDB();
        diffuseurBoxActionPerformed(null);
        annonceurBoxActionPerformed(null);
        metierBoxActionPerformed(null);
        contratBoxActionPerformed(null);

        DefaultListModel listModel;
        listModel = new DefaultListModel();

        // java.util.Arrays.sort(dir);
        OffreDAO offreDAO = new OffreDAO();
        Collection<Offre> offres = OffreDAO.lister(cnx);

        for (Offre offre : offres) {
            // listModel.addElement(offre.getTitre());
            listModel.addElement(offre.getId() + "-" + offre.getTitre());
        }

        modifier_liste.setModel(listModel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSlider1 = new javax.swing.JSlider();
        boutonEnregistrer = new javax.swing.JButton();
        titreBox = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionBox = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        profilBox = new javax.swing.JTextArea();
        dureeContratBox = new javax.swing.JTextField();
        referenceBox = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nombrePosteBox = new javax.swing.JTextField();
        contratBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        annonceurBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        diffuseurBox = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        metierBox = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        date_debut_publi_box = new javax.swing.JTextField();
        date_fin_publi_box = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        modifier_liste = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Modifier Offre");

        boutonEnregistrer.setText("Modifier");
        boutonEnregistrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boutonEnregistrerActionPerformed(evt);
            }
        });

        titreBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titreBoxActionPerformed(evt);
            }
        });

        descriptionBox.setColumns(20);
        descriptionBox.setRows(5);
        descriptionBox.setText("Description de l offre");
        jScrollPane1.setViewportView(descriptionBox);

        profilBox.setColumns(20);
        profilBox.setRows(5);
        profilBox.setText("Profil recherché");
        jScrollPane2.setViewportView(profilBox);

        dureeContratBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dureeContratBoxActionPerformed(evt);
            }
        });

        referenceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceBoxActionPerformed(evt);
            }
        });

        jLabel3.setText("nombrePoste");

        nombrePosteBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePosteBoxActionPerformed(evt);
            }
        });

        contratBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratBoxActionPerformed(evt);
            }
        });

        jLabel4.setText("Contrat");

        annonceurBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annonceurBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Annonceur");

        diffuseurBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diffuseurBoxActionPerformed(evt);
            }
        });

        jLabel6.setText("Diffuseur");

        metierBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metierBoxActionPerformed(evt);
            }
        });

        jLabel7.setText("Metier");

        jLabel2.setText("Date début publication");

        jLabel8.setText("Date fin publication");

        date_debut_publi_box.setText("aaaa-mm-jj");

        date_fin_publi_box.setText("aaaa-mm-jj");

        jLabel1.setText("Titre");

        jLabel9.setText("Référence");

        modifier_liste.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(modifier_liste);

        jButton1.setText("Charger");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel10.setText("Durée du contrat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel1))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(referenceBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titreBox, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dureeContratBox, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(74, 74, 74)))
                        .addComponent(boutonEnregistrer, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(diffuseurBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(contratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(annonceurBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(metierBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(nombrePosteBox, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date_debut_publi_box, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(date_fin_publi_box))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(90, 90, 90))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(titreBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(referenceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombrePosteBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(date_debut_publi_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(date_fin_publi_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(contratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(annonceurBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(diffuseurBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(metierBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dureeContratBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boutonEnregistrer)
                            .addComponent(jLabel10)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boutonEnregistrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boutonEnregistrerActionPerformed

        String selectedValue = modifier_liste.getSelectedValue().toString();
        String[] str = selectedValue.split("-");
        int id = Integer.parseInt(str[0]);

        String titre = titreBox.getText();
        String reference = referenceBox.getText();
        String description = descriptionBox.getText();
        String profil = profilBox.getText();
        String dateDebutPubli = date_debut_publi_box.getText();
        String dateFinPubli = date_fin_publi_box.getText();
        int nombrePoste = Integer.parseInt(nombrePosteBox.getText());
        int dureeContrat = Integer.parseInt(dureeContratBox.getText());

        String libelleContrat = (String) contratBox.getSelectedItem();
        String libelleMetier = (String) metierBox.getSelectedItem();
        String nomAnnonceur = (String) annonceurBox.getSelectedItem();
        String nomDiffuseur = (String) diffuseurBox.getSelectedItem();

//        ContratDAO contratDAO = new ContratDAO();
//        MetierDAO metierDAO = new MetierDAO();
//        AnnonceursDAO annonceurDAO = new AnnonceursDAO();
//        DiffuseursDAO diffuseurDAO = new DiffuseursDAO();
        Offre offre = OffreDAO.trouver(cnx, id);

        if (offre != null) {
            Contrat contrat = ContratDAO.trouver(cnx, libelleContrat);
            Metier metier = MetierDAO.trouver(cnx, libelleMetier);
            Annonceur annonceur = AnnonceursDAO.trouver(cnx, nomAnnonceur);
            Diffuseur diffuseur = DiffuseursDAO.trouver(cnx, nomDiffuseur);

            offre = new Offre(id, titre, reference, dateDebutPubli, dateFinPubli, nombrePoste, description, profil, dureeContrat, contrat, annonceur, diffuseur, metier);

            try {
                String message = OffreDAO.modifier(cnx, offre);
                // JOptionPane.showConfirmDialog(rootPane, "L'offre a bien été créée !");
                JOptionPane.showMessageDialog(rootPane, message);
            } catch (Exception ex) {
                // JOptionPane.showMessageDialog(rootPane, "L'offre n'a pas été créée , vérifer vos champs ");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_boutonEnregistrerActionPerformed

    private void dureeContratBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dureeContratBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dureeContratBoxActionPerformed

    private void referenceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceBoxActionPerformed

    private void nombrePosteBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePosteBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombrePosteBoxActionPerformed

    private void contratBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratBoxActionPerformed
        try {
            String sql = "Select libelle from contrat";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String libelleContrat = rs.getString("libelle");
                contratBox.addItem(libelleContrat);
            }

        } catch (Exception e) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_contratBoxActionPerformed

    private void diffuseurBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diffuseurBoxActionPerformed
        try {
            String sql = "Select nom from diffuseur";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String nomDiffuseur = rs.getString("nom");
                diffuseurBox.addItem(nomDiffuseur);
            }

        } catch (Exception e) {

        }        // TODO add your handling code here:
    }//GEN-LAST:event_diffuseurBoxActionPerformed

    private void annonceurBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annonceurBoxActionPerformed
        try {
            String sql = "Select nom from annonceur";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String nomAnnonceur = rs.getString("nom");
                annonceurBox.addItem(nomAnnonceur);
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_annonceurBoxActionPerformed

    private void metierBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metierBoxActionPerformed
        try {
            String sql = "Select libelle from metier";
            pst = cnx.prepareStatement(sql);
            rs = pst.executeQuery();

            while (rs.next()) {
                String libelleMetier = rs.getString("libelle");
                metierBox.addItem(libelleMetier);
            }

        } catch (Exception e) {

        }
    }//GEN-LAST:event_metierBoxActionPerformed

    private void titreBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titreBoxActionPerformed

    }//GEN-LAST:event_titreBoxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String selectedValue = modifier_liste.getSelectedValue().toString();
        String[] str = selectedValue.split("-");
        int id = Integer.parseInt(str[0]);

        Offre offre = OffreDAO.trouver(cnx, id);
        // offre.getId();
        titreBox.setText(offre.getTitre());
        annonceurBox.setSelectedItem(offre.getAnnonceur().getNom());
        contratBox.setSelectedItem(offre.getContrat().getLibelle());
        profilBox.setText(offre.getDescription_profil());
        descriptionBox.setText(offre.getDescription_poste());
        //diffuseurBox.setSelectedItem(offre.getDiffuseur());
        diffuseurBox.setSelectedItem(offre.getDiffuseur().getNom());
        String duree_contrat = Integer.toString(offre.getDuree());
        dureeContratBox.setText(duree_contrat);
        date_fin_publi_box.setText(offre.getFin_publi());
        metierBox.setSelectedItem(offre.getMetier().getLibelle());
        String nb_poste = Integer.toString(offre.getNbr_poste());
        nombrePosteBox.setText(nb_poste);
        referenceBox.setText(offre.getReference());
        date_debut_publi_box.setText(offre.getDate_debut_publi());
        // int id = offre.getId();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modifierOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modifierOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modifierOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modifierOffre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modifierOffre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox annonceurBox;
    private javax.swing.JButton boutonEnregistrer;
    private javax.swing.JComboBox contratBox;
    private javax.swing.JTextField date_debut_publi_box;
    private javax.swing.JTextField date_fin_publi_box;
    private javax.swing.JTextArea descriptionBox;
    private javax.swing.JComboBox diffuseurBox;
    private javax.swing.JTextField dureeContratBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JComboBox metierBox;
    private javax.swing.JList modifier_liste;
    private javax.swing.JTextField nombrePosteBox;
    private javax.swing.JTextArea profilBox;
    private javax.swing.JTextField referenceBox;
    private javax.swing.JTextField titreBox;
    // End of variables declaration//GEN-END:variables
}
